# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install build dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir hatchling

# Install project with pip
RUN pip install --no-cache-dir .

# Expose the MCP server port if needed (although MCP uses stdio, but if HTTP then expose)
# EXPOSE 8000

# Set the entrypoint command
ENTRYPOINT ["hex-mcp"]
CMD ["run"]
